apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-mongodb-0
  namespace: three-tier
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  volumeName: mongo-pv
  resources:
    requests:
      storage: 1Gi
